### PR TITLE
Update play iteratees dependency to 2.2

### PR DESCRIPTION
**Pull request by kompot**

### CODE REVIEW

**Comment by gre** [comment]
Thanks man. Really appreciate this!

**Comment by kompot** [comment]
Great. Could you please publish new version to a public repository? 
I guess somewhere here
http://mvnrepository.com/artifact/fr.greweb/playcli_2.10?

**Comment by gre** [comment]
Sure, will do ASAP

**Comment by gre** [comment]
It should be now available in maven repository (or in a few hours after full sync),

otherwise I've notice that tests doesn't seem to pass anymore, do you have any clue about this? I'm not sure it's even related to this new play version. I have a lot of Future timeout exception.

**Comment by kompot** [comment]
Yep, I also got lots of Future timeouts (didn't run tests before so maybe they were there before update).

**Comment by gre** [comment]
I'm gonna make a new release which remove the internal implicit `ExecutionContext` to go in phase with the new play iteratees (which now requires to have an imported ExecutionContext), maybe this is also linked to these test error,

what do you think?

Thanks :)

**Comment by kompot** [comment]
Not sure if I can be of any help with that, not too much acquainted with play iteratees, sorry(

**Comment by gre** [comment]
No problem.
Thanks for the help

I'll give another try ASAP
Le 12 oct. 2013 23:13, "Anton Fedchenko" notifications@github.com a écrit
:

**Comment by vjousse** [comment]
When trying to use PlayCLI with Play 2.2.1 I'm getting the following errors:

```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/vjousse/usr/src/scala/speech-recognition-api/}liumsg:
[error]    com.jsuereth:scala-arm _2.10, _2.10.0-RC1
[error]    com.github.scala-incubator.io:scala-io-core _2.10, _2.10.0-RC1
[error]    com.github.scala-incubator.io:scala-io-file _2.10, _2.10.0-RC1
[trace] Stack trace suppressed: run last *:update for the full output.
[error] (*:update) Conflicting cross-version suffixes in: com.jsuereth:scala-arm, com.github.scala-incubator.io:scala-io-core, com.github.scala-incubator.io:scala-io-file
[error] Total time: 2 s, completed Nov 18, 2013 1:52:33 PM
```

I suppose it's related to this issue?

**Pull request merged**
